### ISSUE TITLE
Add LocalWiki?

### ISSUE THREAD

**Issue by philipn** [whosonfirst/whosonfirst-sources#1]
I haven't researched how projects are included here, but it seems LocalWiki would be a good addition to this database. It contains ~100k pages, most of which are places, and almost all of which aren't on Wikipedia. All map data is ODbL and written content & images is CC-BY. We don't have database dumps at the moment, but it's easy to paginate through the API and get whatever you want (e.g. https://localwiki.org/api/v4/maps/)

**Comment by nvkelso** [comment]
Thanks for the tip, @philipn, looks like a useful resource! Can you confirm (via link) to terms of service that including the LocalWiki place IDs in Who's On First as a concordance is compatible with your ODbL license?

**Comment by philipn** [comment]
Yup! See https://localwiki.org/main/Terms_of_Use and https://localwiki.org/main/Copyrights

**Comment by stepps00** [comment]
Follow-up: https://github.com/whosonfirst-data/whosonfirst-data/issues/982
