### ISSUE TITLE
What about http://wikimapia.org/

### ISSUE THREAD

**Issue by sheerun** [whosonfirst/whosonfirst-sources#10]
Do you plan to support it maybe? Or is it supported indirectly?

**Comment by nvkelso** [comment]
Wow, the Wikimapia project has come a long way! The water areas, neighbourhoods, and campus polygons are quite attractive. 

In terms of supporting it, maybe? What kind of support are you thinking about? "Linked data" ala concordances or something deeper?

The Wikimapia license is `CC-BY-SA`, the `CC-BY` part works with Who's On First, the `SA` would need investigating but may work. Relying on Google imagery is a concern (but several base maps are listed for consensus making so there is that). But then on the API page it says "non-commercial" use only, so maybe not?

In the meantime, Wikimapia is supported indirectly: many Who's On First records have concordance with Wikipedia and any Wikimapia record that is also linked to Wikipedia could be given a WOF identifier concordance.

**Comment by trexxx222** [comment]
i dont understan

**Comment by nvkelso** [comment]
There's nothing actionable here at the moment, closing.
