### ISSUE TITLE
Standardize on unknown instead of missing

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-sources#112]
We've used two different "sources" to indicate missing &/or unknown information in Who's On First. We should standardize on just one, I propose keeping `unknown` and marking `missing` deprecated with a related PR in the data repo to toggle them around.

It would also be helpful to report how many records (count and as % of project) and what type of properties they're associated with.

Related: https://github.com/whosonfirst/whosonfirst-sources/issues/65.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L420

**Comment by stepps00** [comment]
List of ids for records that have a "missing" `src:geom`: [missing_src_geom.txt](https://github.com/whosonfirst/whosonfirst-sources/files/2028763/missing_src_geom.txt)
  - Count: 11,656

List of ids for records that have an "unknown" `src:geom`: [unknown_source_geom.txt](https://github.com/whosonfirst/whosonfirst-sources/files/2028765/unknown_source_geom.txt)
  - Count: 1,149

List of ids for records that have an "unknown" `src:geom_alt`: [has_unknown_source_geom_alt.txt](https://github.com/whosonfirst/whosonfirst-sources/files/2028764/has_unknown_source_geom_alt.txt)
  - Count: 560

**Comment by stepps00** [comment]
The linked PRs above swap out "missing" values, replacing them with "unknown". In total, there are 9,917 cases out of ~4.8+ million admin records.

There is no need for code changes; out [export code](https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L462-L464) uses "unknown" when a source is not available.

Once the PRs are merged, we can close this issue out.

**Comment by nvkelso** [comment]
All those PRs look good to me, thanks!
