### ISSUE TITLE
Fix Open Data Paris source

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-sources#117]
This is actually an ODbL source and should be stripped from WOF :\

https://github.com/whosonfirst/whosonfirst-sources/tree/d24c4c9d8b89ac5764eec7258966d145ed43a1a5/sources#open-data-paris

The data work is here: https://github.com/whosonfirst-data/whosonfirst-data/issues/1204. Once that is done this source should be marked deprecated and the license changed to ODbL and note updated to say this was from a bad import that has been reverted.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/pull/1333
