### ISSUE TITLE
WOE DB airport campuses credit

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-sources#128]
Looks like the geometries are coming from Alphashapes + Flickr to me. We should indicate that in the sources `src:via` tag.

**Comment by nvkelso** [comment]
@thisisaaronland do you know where the geoms in WOE-DB come from for timezones? eg: https://spelunker.whosonfirst.org/id/102047343/

**Comment by thisisaaronland** [comment]
Airport shapes are from Alphashapes, yes. 

Timezone shapes are from:

* https://github.com/straup/whereonearth-timezone
* http://efele.net/maps/tz/world/

**Comment by nvkelso** [comment]
Noting here that at the time the tz_world was a self made thing by Eric not the newer OSM related build.

**Comment by thisisaaronland** [comment]
Yeah, the `tz_world` webpage lists the data as CC0.
