### ISSUE TITLE
Add source for Northern Ireland Ordnance Survey

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-sources#141]
https://www.opendatani.gov.uk

Specifically: https://www.opendatani.gov.uk/dataset/osni-open-data-largescale-boundaries-local-government-districts-20121/resource/8de2e22f-ee48-42bc-985a-fe6817f940f8

**Comment by nvkelso** [comment]
This uses the same UK Open Gov't license that we've already given 👍 to so LGTM.

https://www.opendatani.gov.uk/terms-and-conditions
