### ISSUE TITLE
How can we add official data from Catalonia localities?

### ISSUE THREAD

**Issue by geostarters** [whosonfirst/whosonfirst-sources#149]

**Comment by stepps00** [comment]
Hey @geostarters - we'd welcome more current Catalonian locality data.

[Here](https://github.com/whosonfirst/whosonfirst-sources/blob/master/source_template.json) is a template file we use to add a new source to Who's On First. I can add a branch with the a new source file to start.. do you happen to have a link to the locality data and a license associated with that data?

**Comment by stepps00** [comment]
This may also be helpful: https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/1

We are currently updating administrative data in Germany (all placetypes) with more properties and more detailed geometries. It may be helpful to follow along with the changes in that branch, as it will be similar to the work needed to update admin data in Catalonia.

**Comment by geostarters** [comment]
Ok. We prepare our data and send you the information. Thanks!

**Comment by geostarters** [comment]
We fill the template file and we put our data in https://github.com/OpenICGC/limits_administratius.
If you need any more please tell us.
locality data: https://github.com/OpenICGC/limits_administratius/tree/master/data
license associated with that data: Institut Cartogràfic i Geològic de Catalunya (ICGC), under a CC BY 4.0 license

**Comment by stepps00** [comment]
This is great, thank you @geostarters! It looks like this will be a fairly straightforward matching to existing WOF features, and the new geometries look more detailed than existing geometries. The coast of Sitges as an example:

New:
<img width="673" alt="Screen Shot 2019-05-17 at 10 08 31 AM" src="https://user-images.githubusercontent.com/18567700/57944483-053ab980-788c-11e9-8e75-aa22b805588f.png">

Existing:
<img width="443" alt="Screen Shot 2019-05-17 at 10 08 50 AM" src="https://user-images.githubusercontent.com/18567700/57944484-053ab980-788c-11e9-9af1-66231d347893.png">

I'll give this a second look next week and update this issue.

**Comment by stepps00** [comment]
New source has been added [here](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/esp-icgc.json). Tracking data updates in https://github.com/whosonfirst-data/whosonfirst-data/issues/1613, so this issue can be closed.
