### ISSUE TITLE
Python 3 needed for bin/docs.py?

### ISSUE THREAD

**Issue by vicchi** [whosonfirst/whosonfirst-sources#174]
I'm running my whole WOF environment inside a virtual env and prepping `whosonfirst-sources` for a new data source. Running `make all` barfs with unicode vs. utf8 stuff ...

```
$ make all
python ./bin/compile.py > data/sources-spec-`date "+%Y%m%d"`.json
cp data/sources-spec-`date "+%Y%m%d"`.json data/sources-spec-latest.json
python ./bin/docs.py
Traceback (most recent call last):
  File "./bin/docs.py", line 201, in <module>
    _license.write("- **" + str(details['fullname']) + "**: source " + url + ' and ' + license + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 10: ordinal not in range(128)
make: *** [docs] Error 1
```

... which smelt like Python 2.7 vs. 3. Sure enough ...

```
$ which python
/Volumes/BitBucket/wof/venv/bin/python
$ python --version
Python 2.7.17
$ which python3
/usr/local/bin/python3
$ python3 bin/docs.py
```

At the minimum maybe an addition to the README to say that a) Python 3 is required, b) that `python` should point to the Python v3 binary and c) seeing as the scripts in `./bin` have a shebang for Python, just invoke the scripts as `./bin/docs.py` in the `Makefile`?

**Comment by stepps00** [comment]
Thanks @vicchi - I agree that we need to clarify the Python3 requirement in the README of this repo. If you'd like to propose a fix to the README, I'd be more than happy to take a look and merge, otherwise I can add a blurb later this week.

I've run into various Python issues myself lately, so I'll keep in mind that any Python changes to other repos will require a note in other READMEs..

**Comment by vicchi** [comment]
@stepps00 I'll do a PR later today with updates to the docs, plus a proposed workaround to allow this to work for people who have Python 2.7 as their default version, plus some dependencies fixes as well (such as the `ia` target in the `Makefile` needing the `ia` CLI tool pre-installed).

As #175 is pending merge, I'll do this on a different branch as well when submitting the new PR.

**Comment by stepps00** [comment]
@vicchi - I think all of the related PRs have been merged. Are we OK to close this issue?

**Comment by vicchi** [comment]
@stepps00 Absolutely ... closing this down now
