### ISSUE TITLE
Rename default branch to "main"

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-sources#186]
* Create a new `main` branch
* Tell GH that `main` is the default branch, in UI
* Delete `master` branch
 
@stepps - The only reason I assigned this to you rather than just making the change myself is that I know you use this repo a lot and I didn't want to break any tools that might be using the old "master" branch.

If that's not an issue you can a) rename things yourself or b) reassign the issue to me and I will make the changes.

**Comment by stepps00** [comment]
Thanks for the issue.. I'll take a look shortly and give this a shot since there are no open PRs in this repo. If all goes well, I'll try to prioritize this work on the`whosonfirst-data-*` repos, too.

**Comment by stepps00** [comment]
I've created the main branch, here: https://github.com/whosonfirst/whosonfirst-sources/tree/main

Though it looks like I'm unable to complete the next two steps, as I am not an admin of the `whosonfirst` org.. @thisisaaronland is this something you could complete? We should be fine removing the `master` branch without breaking any tools.

**Comment by thisisaaronland** [comment]
Done.
