### ISSUE TITLE
 Correct geometries for the villages and cities in Catalonia (localities)

### ISSUE THREAD

**Issue by geostarters** [whosonfirst/whosonfirst-sources#196]
Sir/Madam,

In 2019 we send you the correct localadmin polygons to improve the existing ones.
Now, we are sending a geojson which contains de correct geometries for the villages and cities in Catalonia: [locality_CAT_fix.geojson]
In a near future we are going to send you complementary polygons of the very small villages.

We fill the template file and we put our data in https://github.com/OpenICGC/limits_administratius.
If you need any more please tell us.

locality_CAT_fix.geojson data: https://github.com/OpenICGC/limits_administratius/tree/master/data

license associated with that data: Institut Cartogràfic i Geològic de Catalunya (ICGC), under a CC BY 4.0 license

**Comment by stepps00** [comment]
Thanks @geostarters - are the three files in this repo the most up-to-date small villages, villages, and cities? https://github.com/OpenICGC/limits_administratius/tree/master/data
