### ISSUE TITLE
What is simplegeo?

### ISSUE THREAD

**Issue by stevevance** [whosonfirst/whosonfirst-sources#2]
I cannot determine what the source called "simplegeo" is because their domain name leads to a GoDaddy parking page. 

Steps to replicate:
1. Click on random item in Who's On First (okay, this won't actually work for you but it's how I started)
2. Arrive on [this personal injury attorney venue's page](https://whosonfirst.mapzen.com/spelunker/id/269901851/). 
3. Note that its source is called "simplegeo" and that its source page is [on the simplegeo.com domain](http://api.simplegeo.com/1.0/features/SG_4KJNd2sQiPMhosIWsLG1lJ_29.742201_-95.377899@1303263009.json). 
4. Find a GoDaddy domain parking page. 
<img width="1440" alt="screenshot 2015-11-28 02 47 16" src="https://cloud.githubusercontent.com/assets/1330459/11450995/5aa0e38e-957a-11e5-9894-cfc7f06a34f7.png">

**Comment by thisisaaronland** [comment]
These are all good points. So we will do the following in (hopefully) short order:

* Update the whosonfirst-source document with a brief description of SimpleGeo, noting in particular that it is no longer an active company

* Update the import script to scrub the SG `url` property for future imports

* Backfill existing imports to scrub the SG `url` property

Thanks and apologies for the confusion.

**Comment by stepps00** [comment]
We now have a [`simplegeo.json`](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/simplegeo.json) source file in this repo. It looks like the `url` properties in our venue records are updated as well. 

@thisisaaronland - is there additional work to do around the SG `url` property? If not, I will close the issue.

**Comment by thisisaaronland** [comment]
Sounds good.
