### ISSUE TITLE
Add a source file for Karmashapes

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-sources#201]
A new dataset of locality (and some neighbourhood) records was created in Nov/Dec 2022, we should be able to use it to fix https://github.com/whosonfirst-data/whosonfirst-data/issues/2027.

Opening this task to create a new source file for this new dataset, Karmashapes.

**Comment by stepps00** [comment]
@justinelliotmeyers :wave: is there a direct download or license url that WOF could point to for the new Karmashapes dataset we plan on importing? Not sure if you've posted the full release anywhere yet..

**Comment by justinelliotmeyers** [comment]
https://karmashapes.wordpress.com/2023/03/05/karmashapes-v0/
