### ISSUE TITLE
Update to include source from concordances

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-sources#3]
See also:

https://github.com/whosonfirst/go-whosonfirst-concordances#wof-concordances-list

**Comment by stepps00** [comment]
List of concordances to add, per `wof-concordances-latest.csv`:

```
4sq:id
dbp:id
faa:code
fb:id
fct:id
fips:code
gn:id
gp:id
hasc:id
iata:code
icao:code
loc:id
mzb:id
nyt:id
oa:id
qs:id
sg:id
tgn:id
wd:id
wk:page
woe:id
```

Additionally, add `LCSH - Geographic`.

**Comment by stepps00** [comment]
Closing this issue - all concordances have json files in this repo. 

`LCSH - Geographic` and `HASC` need .json files, but those sources are being tracked in separate issues ([here](https://github.com/whosonfirst/whosonfirst-sources/issues/5) and [here](https://github.com/whosonfirst/whosonfirst-sources/issues/28)).
