### ISSUE TITLE
Create records for all sources during for the mesoshapes import

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-sources#39]
The recent import of `admin1` and `admin2` features included sources from AOTM, as well as additional authoritative sources. Scrub all `"meso:source"` property values in countries that had new meso features added and create new source files, as needed.

Example: 

The [county feature of Samba](https://github.com/whosonfirst-data/whosonfirst-data/pull/555/files/cdba38408f8616cec167b445389cb3f47daa2425..ce04aa8148131ded258f22d5a3b8a19265c2a778#diff-c506e4f5b487c4ec542048963090c29b) has a `"meso:source"` value of `"EDP"`, though no EDP.json file is currently in the sources folder.

**Comment by stepps00** [comment]
A list of countries from the mesoshapes import that potentially need new source .json files, below. The source and originator source are listed below each country name.

**COUNTRY**

  - **SOURCE**
  - **ORIGINATOR**

Azerbaijan
  - ISCGM
  - State Committee Land and Cartography

Bangladesh
  - GIST
  - National Renewable Energy Laboratory (NREL)

Bolivia
  - IDE-EPB GeoBolivia data portal
  - IDE-EPB GeoBolivia data portal

Burkina Faso
  - OCHA
  - SALB

Cameroon
  - WRI
  - Institut National de la Cartographie

Chad
  - OCHA
  - unknown

Chile
  - Chilean National Library of Congress
  - unknown

Colombia
  - Sala Humanitaria
  - Sala Humanitaria / Instituto Geografico Agustin Codazzi/OCHA

Costa Rica
  - ESRI Open Data
  - Daticos/Geotecnologias S.A.

Democratic Rebublic of Congo
  - OCHA
  - Referenciel Geographique Commun DRC

Egypt
  - J. M.
  - USAID via FOIA

Ethiopia
  - GIST
  - USAID

Gabon
  - WRI
  - Unknown, possibe Projet Forêt et Environnement (PFE-1999/2000) et Institut National de Cartographie (INC)

Gambia
  - OCHA
  - unknown

Georgia
  - GIST
  - ISCGM / geodesyandcartography 

Honduras
  - ISCGM
  - Direccion General de Catastro y Geografia

India
  - Datameet
  - Datameet

Japan
  - GSI
  - Geospatial Information Authority of Japan (GSI)

Kyrgyzstan
  - OCHA
  - Ministry of Emergency Situations of the Kyrgyz Republic

Liberia
  - GIST
  - USAID/OFDA Economic and Humanitarian Assistance

Mali
  - OCHA
  - unknown

Mauritania
  - OCHA
  - unknown

Mauritius
  - ISCGM
  - Ministry of Housing and Lands

Mozambique
  - ISCGM
  - CENACARTA

New Zealand
  - Statistics New Zealand
  - Statistics New Zealand

Nicaragua
  - ISCGM
  - INETER

Niger
  - OCHA
  - unknown

Nigeria
  - OCHA
  - unknown

Palestine
  - OCHA
  - Ministry of planning (Palestinian Authority)

Papua
  - ISCGM
  - National Mapping Bureau

Peru
  - OCHA
  - Instituto Geográfico Nacional

Rwanda
  - J. M.
  - National Institute of Statistics of Rwanda

Senegal
  - OCHA
  - unknown

South Africa
  - J. M.
  - South Africa Municipal Demarcation Board

Taiwan
  - National Land Surveying and Mapping Center
  - National Land Surveying and Mapping Center

Tanzania
  - National Bureau of Statistics
  - National Bureau of Statistics

Togo
  - ISCGM
  - Direction General of Cartography - DGC Togo

Ukraine
  - J. M.
  - OCHA Ukraine ДНВП Картографія

Paraguay
  - DGEEC
  - Republica de Paraguay Dirección General de Estadística, Encuestas y Censos

French Guiana
  - French IGN
  - French IGN

Jamaica
  - Statistical Institute of Jamaica 
  - Statistical Institute of Jamaica 

Macedonia
  - EuroGlobalMap
  - EuroGlobalMap

Israel
  - Justin Meyer
  - Israel Central Bureau of Statistics

Armenia
  - Justin Meyer
  - Acopian Center for the Environment

Libya
  - OCHA HDX
  - Libya Bureau of Statistics and Census (BSC) and IOM

Burundi
  - OCHA HDX
  - IGEBU

Zimbabwe
  - OCHA HDX
  - Zimbabwe Central Statistics Office (ZimStat)

Guinea
  - OCHA HDX
  - WFP; International Organization for Migration

Serbia
  - EuroGlobalMap for Geometry
  - EuroGlobalMap

Indonesia
  - ISCGM
  - Geospatial Information Agency

Iraq
  - ESOC
  - Relief Web Humanitarian Information Center + World Food Program

Serbia
  - EUROGEOGRAPHICS
  - EUROGEOGRAPHICS

**Comment by stepps00** [comment]
Additional sources to add:

Source | Source Name | License Type
-- | -- | --
AOTM | Art of the mappable processed | Undocumented', Attribution Share Alike', Attribution-Non Commercial', Commercial not allowed', Commercial use allowed, no redistribution', Attribution + Notification', humanitarian response/agency purposes'
OCHA_OPEN | OCHA-HDX various open licenses | Attribution', 'Attribution; equivalent to CC BY', 'No access restrictions. Please cite appropriately.No use constraint', 'All allowed', 'Public domain', some N/A
USAID | GIST with USAID as originator | Public Domain
ESOC | Empirical Study of Conflict | Attribution', 'Attribution; equivalent to CC BY', 'No access restrictions. Please cite appropriately.No use constraint'
EGM | Euro Global Map | Attribution', 'Attribution; equivalent to CC BY', 'No access restrictions. Please cite appropriately.No use constraint'
NREL | National Renewable Energy Laboratory | Attribution', 'Attribution; equivalent to CC BY', 'No access restrictions. Please cite appropriately.No use constraint'
WRI | World Resource Institute | Attribution
CNLC | Chilean National Library of Congress | Attribution', 'Attribution; equivalent to CC BY', 'No access restrictions. Please cite appropriately.No use constraint'
SH | Sala Humanitaria | Public Domain
ISCGM | International Steering Committee for Global Mapping | Attribution + Notification
DATAMEET | Datameet | Attribution,  indicate changes, link to license
GSIJ | Geospatial Information Authority of Japan | Attribution', 'Attribution; equivalent to CC BY', 'No access restrictions. Please cite appropriately.No use constraint'
SNZ | Statistics New Zealand | Attribution
NISR | National Institute of Statistics of Rwanda | Attribution
NEURBAN | Natural Earth Urban | ??
SAMDB | South Africa Municipal Demarcation Board | Public Domain, Attribution, Can not be resold as raw data for profit
TNLSMC | National Land Surveying and Mapping Center | Attribution', 'Attribution; equivalent to CC BY', 'No access restrictions. Please cite appropriately.No use constraint'
TNBS | Tanzania National Bureau of Statistics | Not listed (CC-BY IGO)
IDE_EFP | IDE-EPB GeoBolivia data portal | Attribution', 'Attribution; equivalent to CC BY', 'No access restrictions. Please cite appropriately.No use constraint'
ESRI_OPEN | ESRI Open Data - Daticos | Public Domain
EGM | Euro Global Map | CC-BY
ONEC | Oficina Nacional de Estadísticas. Cuba | x-undoc
DGEEC | republica de Paraguay Dirección General de Estadística, Encuestas y Censos | CC-BY
GBOS | Guyana Bureau of Statistics | X-NC
FIGN | French IGN | X-BY
SIJ | Statistical Institute of Jamaica | X-BY
ICBS | Israel Central Bureau of Statistics | X-BY
ACE | Acopian Center for the Environment | Attribution
EDP | European Data Portal | Public Domain
DCW | Digital Chart of the World | Public Domain
ZIMSTAT | Zimbabwe Central Statistics Office (ZimStat) | Public Domain

**Comment by nvkelso** [comment]
@stepps00 This is ripe for the new `src:via` work you've spec'd out in https://github.com/whosonfirst/whosonfirst-sources/pull/110.

**Comment by stepps00** [comment]
@nvkelso - this was not flagged as fixed as a part of #110, but I suspect it can be closed.. anything left here?

**Comment by nvkelso** [comment]
Agree we can close this, thanks!
