### ISSUE TITLE
Quattroshapes: qs vs qs_gp

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-sources#63]
Once https://github.com/whosonfirst-data/whosonfirst-data/issues/107 lands, update the `quattroshapes.json` source to include the prefix of `qs_gp` (for the point gazetteer).

**Comment by nvkelso** [comment]
I think we should specify this as an additional source with it’s own
prefix. Although they have the same “brand name” they were essentially 2
different projects with different sources and methodologies.

**Comment by stepps00** [comment]
Closing issue, this was taken care of via: https://github.com/whosonfirst/whosonfirst-sources/commit/cee74df632e7e7428fbdeee4fc3f28763720c48d
