### ISSUE TITLE
Add census designated places to boundary data

### ISSUE THREAD

**Issue by frankleng** [whosonfirst/whosonfirst-sources#7]
Assuming CDPs were left out because they are not defined in the admin levels, but people do refer to them as if they are cities.

Please include these in the boundary data.

**Comment by nvkelso** [comment]
@frankleng Can you provide specific examples of missing CDP in the USA? They should be included already.

**Comment by riordan** [comment]
@frankleng Many of these are considered `localadmin`s. You may want to check there.

**Comment by frankleng** [comment]
@nvkelso @riordan ah, I was actually talking about https://mapzen.com/data/borders
but the twitter person told me to file a ticket here.
WOF seems to have most CDPs we are missing.

please advise

**Comment by nvkelso** [comment]
Sorry about the confusion between the two datasets and on Twitter:

* https://mapzen.com/data/borders is a occasional dump of the administrative boundaries found in OpenStreetMap. 

* https://whosonfirst.mapzen.com/bundles/ is mostly aggregated from authoritative sources at the national mapping agency level, has stable IDs, and includes full administrative hierarchy, down to neighbourhood polygons.

We generally recommend Who's On First, but if you have a particular feature you want to extract out of OSM, use the "borders" dataset instead.

I'm curious to know more about your project and how easy it is to use Who's On First for it?

**Comment by frankleng** [comment]
@nvkelso sorry for the late reply.
we are trying to use geojsons matched to Google Maps admin levels to drive location based search.

**Comment by nvkelso** [comment]
@frankleng You might try [Mapzen Search](https://mapzen.com/products/search/) which wraps Who's On First (including the data you were looking for) via the open source [Pelias](https://github.com/pelias/pelias) search project.
