### ISSUE TITLE
Don't put Markdown in description fields

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-sources#79]
This breaks code that needs to load the spec dynamically. For example:

```
$> cd go-whosonfirst-sources                                                                                                                     $>make test
if test -d pkg; then rm -rf pkg; fi
if test -d src/github.com/whosonfirst/go-whosonfirst-sources; then rm -rf src/github.com/whosonfirst/go-whosonfirst-sources; fi
mkdir -p src/github.com/whosonfirst/go-whosonfirst-sources/sources
cp sources/*.go src/github.com/whosonfirst/go-whosonfirst-sources/sources
cp *.go src/github.com/whosonfirst/go-whosonfirst-sources/
# github.com/whosonfirst/go-whosonfirst-sources/sources
src/github.com/whosonfirst/go-whosonfirst-sources/sources/spec.go:6: syntax error: unexpected re after top level declaration
src/github.com/whosonfirst/go-whosonfirst-sources/sources/spec.go:6: missing '
```

This is caused by typos like "...This means that you`re free..." and stuff like "...and three-character feature code with a `-` deliminator (like `CC-az1`)..."

Also, look at the difference between the raw text of the example above and the way it gets formatted by GitHub.

The values of the `.json` files should be plain text with no additional (or specific) formatting.

**Comment by stepps00** [comment]
It looks like the following markdown files in the `sources` folder have Markdown characters in the descriptions field: 

- `unlocode.json`
- `zolk.json`

I've updated them and pushed changes to a PR here: https://github.com/whosonfirst/whosonfirst-sources/compare/stepps00/markdown-updates?expand=1

From now on, no markdown characters will be included in the `description` property (or any other field in the source `.json`). We do have `*_remarks.json` files, like [the geoplanet remarks file](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/geoplanet_remarks.md) and [the Natural Earth remarks file](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/naturalearth_remarks.md). 

@thisisaaronland - will these need to be moved out of the `sources` folder?

**Comment by thisisaaronland** [comment]
It's fine to include Markdown in the `*_remarks.json` files.

**Comment by stepps00** [comment]
PR to remove Markdown text was merged, let me know if this is still an issue.

**Comment by thisisaaronland** [comment]
Looks good, thanks.
