### ISSUE TITLE
Zetashapes providing some shady-af geometries

### ISSUE THREAD

**Issue by wboykinm** [whosonfirst/whosonfirst-sources#8]
I appreciate that neighborhood-level gazetteer information that's not restrictively-licensed (scowling at you, Zillow) is hard to come by, but I've come across some examples in Zetashapes that throw the entire credibility of the scale level into question. I might not have noticed at all if whosonfirst didn't claim that [this monstrosity](https://whosonfirst.mapzen.com/spelunker/id/85852901/#11/44.4184/-73.2388) is my home neighborhood:

<img width="649" alt="screenshot 2016-05-08 20 37 50" src="https://cloud.githubusercontent.com/assets/735463/15101405/50928bc8-155d-11e6-8191-578dd77adf2c.png">

Zetashapes does not appear to be accepting edits. @blackmad is a busy guy, so I don't have a lot of hope for the [todo list](http://zetashapes.com/) getting addressed. Is there any downside to Mapzen adopting the zetashapes backend, at least insofar as allowing users to fix [nonsense](https://whosonfirst.mapzen.com/spelunker/id/85895993/#13/39.9984/-105.3490) like [this](https://whosonfirst.mapzen.com/spelunker/id/85855397/#13/43.6414/-70.2751)?

**Comment by thisisaaronland** [comment]
Public-facing editorial tools are (realistically) not a thing that will happen in the short-term, much as people would like.

That being said there aren't / isn't a well-documented way for people to extract a smaller slice of WOF data for doing targeted work on, in QGIS or whatever. It's _possible_ just not well documented. Yet.

There is a similar/related issue [1] and I think that there are enough hooks (in the code) to generate extracts for both cases that it's time to write it all down "on paper".

For Burlington that would mean editing a `FeatureCollection` of records (in QGIS, Arc, PostGIS, whatever) and sending us a pull request. Which isn't ideal but it's a start...

[1] https://github.com/whosonfirst/whosonfirst/issues/2

**Comment by wboykinm** [comment]
@thisisaaronland I'm certainly up for that on my home turf to make it look credible, but that seems a bit unrealistic for the whole dataset, and these seem to be everywhere. 

But as a starting point, where should I add the data and issue the PR? Here? [whosonfirst-data](https://github.com/whosonfirst/whosonfirst-data)?

**Comment by nvkelso** [comment]
@wboykinm Yikes, the shapes in Burlington are terrible! 

We've noticed Zetashapes is good in dense urban areas, but goes [crazy](https://github.com/whosonfirst/whosonfirst-data/issues/149) in rural areas. We'd like to track the general problem in that issue. Usually the alt geoms from Quattroshapes are better / more constrained starting point. See https://github.com/whosonfirst/whosonfirst-data/tree/master/data/858/529/01, for comparison. 

Yes, a PR in https://github.com/whosonfirst/whosonfirst-data for Burlington neighbourhoods would be lovely. Great to have a local expert on board! :)

**Comment by wboykinm** [comment]
Moved this over to [`whosonfirst-data`](https://github.com/whosonfirst-data/whosonfirst-data/issues/434)
