### ISSUE TITLE
Verify the license terms for the following sources

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-sources#92]
Verify the following source terms and license URLs... (_see notes_):

- [x] [woedb](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#woe-db)
- [x] [zetashapes](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#zetashapes)
- [x] [yerbashapes](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#yerbashapes)
- [x] [seagv](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#Seattle-City-GIS-Program)
- [x] [wapo](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#Washington-Post)
- [x] [sjp](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#san-jose-planning-department)
- [x] [unknown](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#unknown)
- [x] [sfgov](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#city-of-san-francisco)
- [x] [oakced](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#oakland-community-and-economic-development-department)
- [x] [nolagis](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#city-of-new-orleans-office-of-information-technology-and-innovation-enterprise-information-team)
- [x] [stpaulgov](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#open-information-saint-paul)
- [x] [minitenders](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#mini-tenders)
- [x] [camgov](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#city-of-cambridge-geographic-information-system-department)
- [x] [burritojustice](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#burrito-justice) (https://github.com/whosonfirst/whosonfirst-sources/commit/7f92b7b04a0a17b7a5253f28850fa571faaefce6)
- [x] [simplegeo](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md#simplegeo)

**Comment by stepps00** [comment]
README: https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md

**Comment by nvkelso** [comment]
For Burrito Justice:

- https://burritojustice.com/licensing/

**Comment by nvkelso** [comment]
For Mapzen mark as CC0 license:

`Remember, some sources require attribution, some do not. Mapzen's original work, including the format and structure that allows Who's On First to operate, is made available under the Creative Commons Zero designation, and a shout out would be lovely.`

https://github.com/whosonfirst-data/whosonfirst-data/blob/master/LICENSE.md#license

**Comment by nvkelso** [comment]
For `wapo`: 

https://web.archive.org/web/20160209065412/http://opendatadc.org/dataset/neighborhood-boundaries-217-neighborhoods-washpost-justgrimes

**Comment by nvkelso** [comment]
for `frgov`:

License link should point to data license not website terms:

- https://www.etalab.gouv.fr/wp-content/uploads/2014/05/Open_Licence.pdf

**Comment by stepps00** [comment]
https://github.com/whosonfirst/whosonfirst-sources/issues/92#issuecomment-388473529 / BurritoJustice: license pointer [here](https://github.com/whosonfirst/whosonfirst-sources/pull/110/files#diff-94b80d5ac047e992fdaf419462fb6fdd).

https://github.com/whosonfirst/whosonfirst-sources/issues/92#issuecomment-388507213 / Mapzen: updated license and link [here](https://github.com/whosonfirst/whosonfirst-sources/pull/110/commits/924162496411bad27f6812a988e0ab79c34736f0).

https://github.com/whosonfirst/whosonfirst-sources/issues/92#issuecomment-389332492 / LA Times: marked as only concordance usage [here](https://github.com/whosonfirst/whosonfirst-sources/pull/110/files#diff-b7ef81174d806baaf64c79cc7cc394cf).

https://github.com/whosonfirst/whosonfirst-sources/issues/92#issuecomment-389694973 / Wapo: updated license link [here](https://github.com/whosonfirst/whosonfirst-sources/pull/110/files#diff-11dd53fdaf3e77b01627ab7d661128c9).

https://github.com/whosonfirst/whosonfirst-sources/issues/92#issuecomment-389701532 / frgov: updated license link [here](https://github.com/whosonfirst/whosonfirst-sources/pull/110/files#diff-c6f9e1903bd96d4309f894b3ca32bccb).

**Comment by stepps00** [comment]
Tagging the above sources as complete, as the `usage*` tags flushed out in #110. There may be additional work to validate these sources, but I'd prefer that move to #98.

Closing.
