### ISSUE TITLE
Indicate if source uses geometry, properties, &/or concordances

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-sources#97]
Sometimes we include a source just for concordance IDs because the license is otherwise locked down for geometry &/or properties. But right now that's not documented, and the license may make it seem like we shouldn't use it (but concordances alone is fine).

**Comment by stepps00** [comment]
So called "restricted" sources.

**Comment by nvkelso** [comment]
By the time the big [README.md](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md) is constructed using the per src JSON ([example](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/acgov.json)), the docs generator [script](https://github.com/whosonfirst/whosonfirst-sources/blob/master/bin/docs.py) should read new properties and add a bullet point like:

* usage: `concordance`, `properties`, `geometry` 

Where if the source JSON is true for that usage, it prints it out, otherwise leaves it blank.

Please also add script to crawl the data repo(s) and update the source JSON files for the usage. Practically speaking let's limit this to `whosonfirst-data` for now.
